# Generated by Django 3.2.7 on 2021-10-13 19:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Active'),
        ),
        migrations.AlterField(
            model_name='course',
            name='group_weight',
            field=models.PositiveSmallIntegerField(default=40, verbose_name='Group Weight'),
        ),
        migrations.AlterField(
            model_name='course',
            name='individual_weight',
            field=models.PositiveSmallIntegerField(default=60, verbose_name='Individual Weight'),
        ),
        migrations.AlterField(
            model_name='developer',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='lecturer',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('github', models.CharField(max_length=512, null=True, verbose_name='Git Page')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.course')),
                ('supervisor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tasks.lecturer')),
            ],
        ),
        migrations.CreateModel(
            name='Milestone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Milestone')),
                ('description', models.TextField(verbose_name='Milestone Details')),
                ('weight', models.PositiveSmallIntegerField(default=30, verbose_name='Weight')),
                ('due', models.DateField(verbose_name='Due Date')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.course')),
            ],
        ),
        migrations.AddField(
            model_name='developer',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tasks.team'),
        ),
    ]
