# Generated by Django 3.2.7 on 2021-10-13 20:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_auto_20211013_1932'),
    ]

    operations = [
        migrations.CreateModel(
            name='MasterTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('milestone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.milestone')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.developer')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.team')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, verbose_name='Brief Task Title')),
                ('description', models.TextField(verbose_name='Description')),
                ('promised_date', models.DateField(verbose_name='Promised Date')),
                ('masterTask', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.mastertask')),
            ],
        ),
    ]
