# Generated by Django 3.2.7 on 2021-10-16 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_mastertask_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='mastertask',
            name='completed',
            field=models.DateField(null=True, verbose_name='Completion Date'),
        ),
    ]
