# Generated by Django 3.2.7 on 2021-10-29 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_auto_20211028_0904'),
    ]

    operations = [
        migrations.AddField(
            model_name='mastertask',
            name='difficulty',
            field=models.PositiveSmallIntegerField(choices=[(3, 'Difficult'), (2, 'Normal'), (1, 'Easy')], default=2, verbose_name='Difficulty'),
        ),
        migrations.AddField(
            model_name='mastertask',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Proposed'), (2, 'Open'), (3, 'Completed'), (4, 'Rejected'), (5, 'Accepted')], default=2, verbose_name='Status'),
        ),
        migrations.AddField(
            model_name='task',
            name='priority',
            field=models.PositiveSmallIntegerField(choices=[(3, 'Urgent'), (2, 'Planned'), (1, 'Low')], default=2, verbose_name='Priority'),
        ),
    ]
