# Generated by Django 3.2.7 on 2021-10-31 20:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tasks', '0006_auto_20211029_2049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mastertask',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Proposed'), (2, 'Open'), (3, 'Completed'), (4, 'Rejected'), (5, 'Accepted')], default=1, verbose_name='Status'),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(verbose_name='Comment')),
                ('file_url', models.URLField(blank=True, max_length=512, null=True, verbose_name='File URL')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Date')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.mastertask')),
            ],
        ),
    ]
