# Generated by Django 3.2.7 on 2021-11-02 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0008_auto_20211031_2057'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='approved',
            field=models.BooleanField(blank=True, null=True, verbose_name='Approved'),
        ),
    ]
