# Generated by Django 3.2.7 on 2021-11-03 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0011_auto_20211102_1957'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='version',
            field=models.IntegerField(default=1, verbose_name='version'),
        ),
    ]
