# Generated by Django 3.2.7 on 2021-11-22 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0016_mastertasklog_gizli'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mastertasklog',
            name='tarih',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date'),
        ),
    ]
