# Generated by Django 3.2.7 on 2021-11-26 18:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0017_alter_mastertasklog_tarih'),
    ]

    operations = [
        migrations.CreateModel(
            name='MilestoneGrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.PositiveSmallIntegerField(default=0, verbose_name='Grade')),
                ('milestone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.milestone')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.team')),
            ],
        ),
    ]
