# Generated by Django 4.1 on 2022-10-03 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0019_rename_milestonegrade_teammilestonegrade'),
    ]

    operations = [
        migrations.AddField(
            model_name='mastertask',
            name='created',
            field=models.DateTimeField(null=True, verbose_name='Creation Date'),
        ),
        migrations.AlterField(
            model_name='mastertask',
            name='completed',
            field=models.DateTimeField(null=True, verbose_name='Completion Date'),
        ),
    ]
