# Generated by Django 4.1.2 on 2022-10-10 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0020_mastertask_created_alter_mastertask_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='developer',
            name='photoURL',
            field=models.URLField(default='https://cdn0.iconfinder.com/data/icons/social-media-network-4/48/male_avatar-512.png'),
        ),
    ]
