# Generated by Django 4.1 on 2022-10-16 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0021_developer_photourl'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mastertask',
            name='created',
        ),
        migrations.AddField(
            model_name='mastertask',
            name='opened',
            field=models.DateTimeField(null=True, verbose_name='Opened Date'),
        ),
        migrations.AlterField(
            model_name='developer',
            name='photoURL',
            field=models.URLField(blank=True, default='https://cdn0.iconfinder.com/data/icons/social-media-network-4/48/male_avatar-512.png'),
        ),
    ]
